FROM tomcat:8.0-alpine
# MAINTAINER <abeyrhurtis@cs.ajce.in>

LABEL maintainer="abeyrhurtis@cs.acje.in"

#docker run -p 8080:8080 tomcatimage
#docker run -p 8080:8080 tomcat_docker_id

ADD sample.war /user/local/tomcat/webapps/

EXPOSE 8080

# CMD ["cataline.sh", "run"]


