apiVersion: v1
kind: PersistentVolume
metadata:
    name: jenkins-pv 
    namespace: jenkins-demo
spec:
    storageClassName: jenkins-Pv
    accessModes:
      - ReadWriteOnce
    capacity:
        storage: 2Gi
    PresistentVolumeReclaimPolicy: Retain
    hostPath:
        path: /data/jenkins-volume/