- name: Tomcat installation 
  hosts: allocated
  tasks:

  - name : Install Dependencies 
    package: 
      name: java
      state: present 

  - name: Download Tomat and extract 
    unarchive:
      src: https://downloads.apache.org/tomcat/tomcat-8/v8.5.58/bin/apache-tomcat-8.5.58.tar.gz
      dest: /opt/tomcat/
      remote_src: yes
      extra_opts: [--strip-components=1]

  - name: Copy service file 
    copy:
      src: tomcat.service
      dest: /etc/systemd/system/
      mode: 755

  - name: start tomcat service 
    service:
      name: tomcat
      state: started 
      enabled: yes 
      

